project_id = "chlqpvzreztzxmjjdjpk"

[functions.auto-generate-country-options]
verify_jwt = true

[functions.badge-service-api]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.generate-badge-image]
verify_jwt = true

[functions.seed-badges]
verify_jwt = true

[functions.test-ai-provider]
verify_jwt = true