project_id = "chlqpvzreztzxmjjdjpk"

[functions.seed-documentation]
verify_jwt = false

[functions.knowledge-chat]
verify_jwt = false

[functions.download-all-documentation]
verify_jwt = true

[functions.auto-generate-country-options]
verify_jwt = true

[functions.badge-service-api]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.generate-badge-image]
verify_jwt = true

[functions.reset-team-member-password]
verify_jwt = false

[functions.seed-badges]
verify_jwt = true

[functions.test-ai-provider]
verify_jwt = true

[functions.simulator-get-profile]
verify_jwt = false

[functions.create-simulator-session]
verify_jwt = true

[functions.generate-question-text]
verify_jwt = true

[functions.generate-question-options]
verify_jwt = true